name: Daily professional commits

on:
  schedule:
    - cron: '0 9 * * *' # every day at 9:00 UTC
  workflow_dispatch: # manual trigger

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update README and commit
        run: |
          FILE="README.md"
          DATE=$(date '+%Y-%m-%d')

          if grep -q "Last updated:" $FILE; then
            sed -i "s/Last updated:.*/Last updated: $DATE/" $FILE
          else
            echo -e "\n## Daily Contributions\nLast updated: $DATE" >> $FILE
          fi

          git config user.name "Tanmay Zade"
          git config user.email "tanmayzade2002@gmail.com"
          git add $FILE
          git commit -m "Daily update: $DATE" || echo "No changes to commit"
          git push
